refactor: use lowercase discord.js everywhere
discordjs/guide pull request #1015
Opened 2022-01-30 21:19 UTC by GodderE2D

**Please describe the changes this PR makes and why it should be merged:**

The main site ([discord.js.org](https://discord.js.org)) uses lowercase discord.js, and so does the server. This pull request changes all "Discord.js" instances to "discord.js". I have no idea if this is going to break anything as getting up a local version didn't work for me, so the deploy preview is my friend :D

2022-03-01 11:02 UTC, almostSouji requested changes
Unsure about the other ones, cc @Danktuary , but the one I marked definitely needs to be capital, as it's the beginning of a sentence in a paragraph

2022-03-01 11:02 UTC, almostSouji commented on guide/miscellaneous/parsing-mention-arguments.md
> +discord.js is already geared to help you handle mentions using `message.mentions`.
Revert, beginning of a sentence

2022-03-02 10:15 UTC, GodderE2D commented
(For above commit) I'm not sure if that counts as a sentence because it is a heading, should I revert that?

2022-03-02 10:20 UTC, almostSouji approved these changes
No, you're right, headings, too, should be capital

2022-03-02 10:21 UTC, merged