fix(examples): Improve examples
discordjs/guide pull request #1212
Opened 2022-07-27 01:43 UTC by isaacKenyon

**Please describe the changes this PR makes and why it should be merged:**
This PR aims to address the concerns brought up in #1147.

2022-07-27 02:52 UTC, isaacKenyon commented
Should the spelling within the changes become Americanised?

2022-07-27 08:46 UTC, megatank58 commented
A command which asks questions doesn't seems like a good use case for something like autocomplete- the point of which is to provide dynamic options

2022-08-29 10:22 UTC, almostSouji requested changes
address lint warnings

2022-08-29 10:25 UTC, almostSouji requested changes

2022-08-29 10:25 UTC, almostSouji commented on guide/interactions/autocomplete.md
> +			const choices = ['Popular Topics: Threads', 'Sharding: Getting started', 'Library: Voice Connections', 'Interactions: Replying to slash commands', 'Popular Topics: Embed preview'];
that const seems very wrong here

2022-08-31 07:05 UTC, almostSouji approved these changes

2022-08-31 07:06 UTC, merged