Update changes-in-v14.md
discordjs/guide pull request #1220
Opened 2022-07-31 16:05 UTC by rmlgaming

This tripped me up for a few hours; the v14 discord API wasn't complaining that I was using `"BUTTON"` over `ComponentType.Button` like it would when I used `"PRIMARY"` over `ButtonStyle.Primary`. I feel like this could save others some time! Thanks.

2022-07-31 16:23 UTC, megatank58 commented
this should be added under the heading collector as this is not entirely related to just button data

2022-08-01 05:33 UTC, samast2010 requested changes
Just a typo

2022-08-01 05:33 UTC, samast2010 commented on guide/additional-info/changes-in-v14.md
> ++ const { ComopnentType } = require('discord.js');
```suggestion
+ const { ComponentType } = require('discord.js');
```

2022-08-29 09:25 UTC, almostSouji requested changes

2022-08-29 09:25 UTC, almostSouji commented on guide/additional-info/changes-in-v14.md
> +
As said above, this does not go under the Button Data changes, but collectors.

2022-09-22 16:50 UTC, almostSouji approved these changes

2022-09-22 16:52 UTC, merged