feat: Update guide to discord.js 14.8.0
discordjs/guide pull request #1420
Opened 2023-02-22 18:09 UTC by Jiralite

**Please describe the changes this PR makes and why it should be merged:**
Adding 14.8.0 changes.

I purposefully did not add the version here. This is an update guide for version 13 users—when they install discord.js v14 for the first time, they would already have access to all these features. In the future, the other ones will be removed.

2023-02-22 18:43 UTC, almeidx requested changes

2023-02-22 20:56 UTC, almeidx approved these changes

2023-02-24 16:49 UTC, almostSouji commented
would it be feasible to add the version it was introduced in in the updating section changes? `(as of xx.yy.zz)` /  `(xx.yy.zz or higher)` or sth like that?

2023-02-24 16:51 UTC, Jiralite commented
I was thinking along the lines of actually omitting that. This page is written primarily for users who are in the process of switching from version 13 to version 14, and they don't need to concern themselves with what version they're installing (because it would of course be the lastest 14.x).

2023-02-24 16:55 UTC, almostSouji commented
> (because it would of course be the lastest 14.x).

Unless they follow some outdated tutorial that pins the version, but we cannot avoid that.
Agreed, keep it as it is

2023-02-24 17:35 UTC, jaw0r3k commented
May you mention that GuildModeration intent is needed to use it?

2023-02-24 17:47 UTC, jaw0r3k commented on guide/popular-topics/audit-logs.md
> +		console.log(`A message by ${target.author.tag} was deleted by ${user.tag}.`);
```suggestion
		console.log(`A message by ${target.tag} was deleted by ${user.tag}.`);
```

target actually is an user 
https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/GuildAuditLogsEntry.js#L309

2023-02-25 09:31 UTC, almostSouji requested changes
nitpicks and wording improvements

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +Keep in mind that these examples explore a straightforward case and are no means foolproof. Their purpose is to teach how audit logs work, and expansion of these examples is likely needed to suit you
```suggestion
Keep in mind that these examples explore a straightforward case and are by no means exhaustive. Their purpose is to teach you how audit logs work, and expansion of these examples is likely needed to suit your specific use case.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +Let's start by glancing at the <DocsLink path="class/Guild?scrollTo=fetchAuditLogs" type="method" /> method and how to work with it. Using this method requires the `ViewAuditLog` permission. Like man
could link promise/collection to the relevant sections

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +Let's start by glancing at the <DocsLink path="class/Guild?scrollTo=fetchAuditLogs" type="method" /> method and how to work with it. Using this method requires the `ViewAuditLog` permission. Like man
```suggestion
Let's start by glancing at the <DocsLink path="class/Guild?scrollTo=fetchAuditLogs" type="method" /> method and how to work with it. Using this method requires the `ViewAuditLog` permission. Like many discord.js methods, it returns a `Promise` containing the <DocsLink path="class/GuildAuditLogs" /> object. This object has one property, `entries`, which holds a collection of <DocsLink path="class/GuildAuditLogsEntry" /> objects, and consequently, the information you want to retrieve.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +This will return the first entry where an invite was created. We used `limit: 1` here to specify only one entry.
```suggestion
This will return the first entry where an invite was created. You used `limit: 1` here to specify only one entry.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +Audit logs may be received via the gateway event `guildAuditLogEntryCreate` with the `GuildModeration` intent. This is the best way to receive audit logs if you are monitoring them. As soon as a mess
```suggestion
Audit logs may be received via the gateway event `guildAuditLogEntryCreate` and require your application to connect with the `GuildModeration` intent. This is the best way to receive audit logs if you want to monitor them. As soon as a message is deleted, or an invite or emoji is created, your application will receive an instance of this event. A common use case is to find out _who_ did the action that caused the audit log event to happen.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +Audit logs may be received via the gateway event `guildAuditLogEntryCreate` with the `GuildModeration` intent. This is the best way to receive audit logs if you are monitoring them. As soon as a mess
can also link intents to the relevant guide section

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +One of the most common use cases for audit logs would be understanding who deleted any given message in a Discord server. If another user deleted another user's message, you can find out who did that
```suggestion
One of the most common use cases for audit logs is understanding who deleted a message in a Discord server. If a user deleted another user's message, you can find out who did that as soon as you receive the corresponding audit log event.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Define our variables.
```suggestion
	// Define your variables.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Ensure we have the executor cached.
```suggestion
	// Ensure the executor is cached.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +		// We have the message object cached. We can provide a good log here.
```suggestion
		// The message object is in the cache and you can provide a detailed log here.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +		// We did not have the message object cached. We can still emit some information.
```suggestion
		// The message object was not cached but you can still retrieve some information.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Define our variables.
```suggestion
	// Define your variables.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Ensure we have the executor cached.
```suggestion
	// Ensure the executor is cached.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Ensure we have the kicked guild member cached.
```suggestion
	// Ensure the kicked guild member is cached.
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +	// Now we can log the output!
```suggestion
	// Now you can log the output!
```

2023-02-25 09:31 UTC, almostSouji commented on guide/popular-topics/audit-logs.md
> +If you want to check who banned a user, it's actually the same example as above except you should check for the `AuditLogEvent.MemberBanAdd` `action`.
```suggestion
If you want to check who banned a user, it's actually the same example as above except for the `action`. You need to provide `AuditLogEvent.MemberBanAdd` for this case.
```

2023-02-25 10:07 UTC, almostSouji approved these changes

2023-02-25 10:07 UTC, merged