fix(command-handling): use handler for command categories
discordjs/guide pull request #1515
Opened 2023-11-06 22:16 UTC by Idris1401

**Please describe the changes this PR makes and why it should be merged:**

The handler on the Command handling page doesn't work for command categories.

2023-11-06 22:25 UTC, almeidx requested changes

2023-11-06 22:25 UTC, almeidx commented on guide/creating-your-bot/command-handling.md
> +```js {3-18}
```suggestion
```js {3-19}
```

2023-11-13 19:56 UTC, Jiralite approved these changes

2023-11-21 19:46 UTC, Jiralite requested changes

2023-11-21 19:46 UTC, Jiralite commented on guide/creating-your-bot/command-handling.md
> +First, [`path.join()`](https://nodejs.org/api/path.html) helps to construct a path to the `commands` directory. The first [`fs.readdirSync()`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_op
```suggestion
First, [`path.join()`](https://nodejs.org/api/path.html) helps to construct a path to the `commands` directory. The first [`fs.readdirSync()`](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options) method then reads the path to the directory and returns an array of all the folder names it contains, currently `['fun', 'moderation', 'utility']`. The second `fs.readdirSync()` method reads the path to these directories and returns an array of all the file names they contain, currently `['ping.js', 'kick.js', 'prune.js', 'avatar.js', 'server.js', 'user.js']`. To ensure only command files get processed, `Array.filter()` removes any non-JavaScript files from the array.
```

2023-11-21 19:47 UTC, Jiralite approved these changes

2023-11-21 19:47 UTC, merged