Added freecodecamp.org link
discordjs/guide pull request #667
Opened 2021-05-14 00:30 UTC by theblobscp

**Please describe the changes this PR makes and why it should be merged:**
I learned pretty much everything from freecodecamp.org, I wanted to let others know about it. It adds a link to freecodecamp.org, and should be added due to how popular it is for learning how to code

2021-05-20 05:05 UTC, J-Human commented
freeCodeCamp would be a good site to learn web development, so it would be good if it was added. But, I think the text that is shown in the hyperlink should be more specific, in terms of how freeCodeCamp would help with JavaScript itself (since the motive of the first page is to tell people to learn so, if they need to).

2021-05-20 22:12 UTC, theblobscp commented
Anything in particluar? I kinda suck at naming things

2021-05-20 23:41 UTC, J-Human requested changes

2021-05-20 23:41 UTC, J-Human commented on guide/README.md
> +* [Freecodecamp, where you can learn other stuff as well](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
```suggestion
* [Freecodecamp, a popular site to learn web development, including JavaScript](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
```

2021-05-21 00:23 UTC, theblobscp commented
I added your changes

2021-06-18 15:23 UTC, Danktuary commented
Sorry for the delayed response, but I don't think we need any more resources listed than what we already have. 😅

2021-06-18 15:23 UTC, closed without merging