Update embeds.md
discordjs/guide pull request #690
Opened 2021-07-02 13:10 UTC by iDrunK65

- Change embed description limit

**Please describe the changes this PR makes and why it should be merged:**

2021-07-02 13:18 UTC, iDrunK65 commented on guide/popular-topics/embeds.md
> +- The footer text is limited to 4096 characters
oops thanks I changed it

2021-07-02 13:21 UTC, almostSouji requested changes
> - A bot can have one embed per message
> - A webhook can have ten embeds per message

Is not true anymore. Bots can now also have up to 10 embeds per message. Could be rephrased to something like `A message can have up to 10 embeds`

2021-07-02 17:38 UTC, almostSouji commented
can generalize the two points and replace them with one

2021-07-03 02:50 UTC, monbrey commented
@almostSouji @iDrunK65 if this is to be a v13-based update to this page with the changes to how many embeds can be sent, then the Attaching Files section should change too

2021-07-03 06:16 UTC, almostSouji commented
no, PR's under the v12 completion milestone are supposed to release under v12

2021-07-03 06:36 UTC, almostSouji approved these changes

2021-07-03 06:38 UTC, merged