feat: v13 `Webhooks`.
discordjs/guide pull request #700
Opened 2021-07-10 14:38 UTC by WiseDevHelper

**Please describe the changes this PR makes and why it should be merged:**

[Demo](https://deploy-preview-700--discordjs-guide.netlify.app/preparations/)

This PR updates the `Preparations` section of the guide for the `v13` release.

**Status**
- [x] Update `Webhooks`.

Please let me know if there is more to change. I'll be happy to work on them.

2021-07-10 14:43 UTC, WiseDevHelper commented
Should I replace the code for the parts where we have examples for `Webhook` and `WebhookClient` with only the essential corresponding function like the previous parts?

2021-07-10 17:53 UTC, Danktuary requested changes
The examples for fetching/editing/deleting are repetitive and share the same methods whether on a Webhook or WebhookClient. They can all be shortened

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +Webhooks are a utility used to send messages to text channels without needing a Discord application. Webhooks are useful for allowing something to send messages without requiring a Discord applicatio
```suggestion
Webhooks are a utility used to send messages to text channels without needing a Discord application. Webhooks are useful for allowing something to send messages without requiring a Discord application. You can also directly edit or delete messages you sent through the webhook. There are two structures to make use of this functionality: `Webhook` and `WebhookClient`. `WebhookClient` is an extended version of a `Webhook`, which allows you to send messages through it without needing a bot client.
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +Webhooks can send messages to a text channel, and fetch, edit, delete the messages sent by them without having to log in as a bot. Discord.js implements a variety of methods to fetch, create, edit, a
```suggestion
Webhooks can send messages to a text channel without having to log in as a bot. They can also fetch, edit, and delete their own messages. There are a variety of methods in discord.js to interact with webhooks. In this section, you will learn how to create, fetch, edit, and use webhooks.
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +Discord.js provides a method for creating webhooks called <DocsLink path="class/TextChannel?scrollTo=createWebhook">`TextChannel#createWebhook()`</DocsLink>.
```suggestion
Webhooks can be created with the <DocsLink path="class/TextChannel?scrollTo=createWebhook">`TextChannel#createWebhook()`</DocsLink> method.
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +You can send messages, fetch, edit and delete messages sent by the Webhook.
```suggestion
Webhooks can send messages to text channels, as well as fetch, edit, and delete their own. These methods are the same for both `Webhook` and `WebhookClient`.
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +Webhooks, like bots, can send up to 10 embeds per message. They can also send attachments and normal content. The <DocsLink path="class/Webhook?scrollTo=send">`Webhook#send()`</DocsLink> method to se
```suggestion
Webhooks, like bots, can send up to 10 embeds per message. They can also send attachments and normal content. The <DocsLink path="class/Webhook?scrollTo=send">`Webhook#send()`</DocsLink> method used to send to a webhook is very similar to the method used for sending to a text channel. Webhooks can also choose how the username and avatar will appear when they send the message.
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +	const channel = client.channels.cache.get('1234567890123456');
```suggestion
	const channel = client.channels.cache.get('123456789012345678');
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +		console.error('Error trying to send a message: ', error);
```suggestion
		console.error('Error trying to send a message:', error);
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +client.login(token);
```suggestion
You can use <DocsLink path="class/Webhook?scrollTo=fetchMessage">`Webhook#fetchMessage()`</DocsLink> to fetch messages previously sent by the Webhook.

```js
const message = await webhookClient.fetchMessage('123456789012345678');
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
> +client.login(token);
```suggestion
You can use <DocsLink path="class/Webhook?scrollTo=editMessage">`Webhook#editMessage()`</DocsLink> to edit messages previously sent by the Webhook.

<!-- eslint-skip -->

```js
const message = await webhook.editMessage('123456789012345678', {
	content: 'Edited!',
	username: 'some-username',
	avatarURL: 'https://i.imgur.com/wSTFkRM.png',
	embeds: [embed],
});
```

2021-07-10 17:53 UTC, Danktuary commented on guide/popular-topics/webhooks.md
```suggestion
You can use <DocsLink path="class/Webhook?scrollTo=deleteMessage">`Webhook#deleteMessage()`</DocsLink> to delete messages previously sent by the Webhook.

<!-- eslint-skip -->

```js
await webhookClient.deleteMessage('123456789012345678');
```
There's a `client.login()` line below that should be deleted (can't reach it via suggestions)

2021-07-19 01:43 UTC, Danktuary approved these changes

2021-07-19 08:38 UTC, almostSouji approved these changes

2021-07-19 08:38 UTC, merged