feat: v13 `Permissions`.
discordjs/guide pull request #705
Opened 2021-07-13 11:00 UTC by WiseDevHelper

**Please describe the changes this PR makes and why it should be merged:**

[Demo](https://deploy-preview-705--discordjs-guide.netlify.app/popular-topics/permissions.html)

This PR updates the `Permissions` section of the guide for the `v13` release.

**Status**
- [x] Update `Permissions`.
- [x] Update `Permissions (extended)`.

Please let me know if there is more to change. I'll be happy to work on them.

2021-07-13 11:47 UTC, almostSouji requested changes
Also needs to address code samples (remove the v11/v12 subfolders)

2021-07-19 02:05 UTC, Danktuary reviewed
Small nitpicks, looks good otherwise

2021-07-19 02:05 UTC, Danktuary commented on guide/popular-topics/permissions.md
> +// editing overwrites with PermissionOverwriteOptions
```suggestion
```

2021-07-19 02:05 UTC, Danktuary commented on guide/popular-topics/permissions.md
> +Discord.js features two utility methods to easily determine the final permissions for a guild member or role in a specific channel: `.permissionsFor()` on the <DocsLink path="class/GuildChannel?scrol
```suggestion
There are two utility methods to easily determine the final permissions for a guild member or role in a specific channel: `.permissionsFor()` on the <DocsLink path="class/GuildChannel?scrollTo=permissionsFor">GuildChannel</DocsLink> class and `.permissionsIn()` on the <DocsLink path="GuildMember?scrollTo=permissionsIn">GuildMember</DocsLink> and <DocsLink path="class/Role?scrollTo=permissionsIn">Role</DocsLink> classes. Both return a <DocsLink path="class/Permissions">Permissions</DocsLink> object.
```

2021-07-19 08:36 UTC, almostSouji approved these changes

2021-07-19 08:36 UTC, merged