feat(EventHandling): use interactions
discordjs/guide pull request #714
Opened 2021-07-15 11:49 UTC by J-Human

**Please describe the changes this PR makes and why it should be merged:**
This makes use of the interaction event and replaces the message one with the former, this would be similar to the command handling counterpart.

2021-07-15 17:32 UTC, WiseDevHelper requested changes
LGTM, Just a small suggestion.

2021-07-15 17:32 UTC, WiseDevHelper commented on code-samples/event-handling/file-setup/events/interactionCreate.js
> +		console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction`);
```suggestion
		console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction.`);
```

2021-07-15 17:32 UTC, WiseDevHelper commented on guide/event-handling/README.md
> +	console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction`);
```suggestion
	console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction.`);
```

2021-07-15 17:33 UTC, WiseDevHelper commented on guide/event-handling/README.md
> +		console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction`);
```suggestion
		console.log(`${interaction.user.tag} in #${interaction.channel.name} triggered an interaction.`);
```

2021-07-15 23:35 UTC, J-Human commented
Gotta add a v13/v12 folder for legacy users.

2021-07-15 23:41 UTC, J-Human commented
\* ready

2021-07-16 00:33 UTC, J-Human commented
All good!

2021-07-16 01:03 UTC, monbrey commented
> 
> 
> Gotta add a v13/v12 folder for legacy users.

I dont think that's right. v11 and v12 content is going to be archived.

2021-07-16 01:04 UTC, J-Human commented
> > Gotta add a v13/v12 folder for legacy users.
> 
> I dont think that's right. v11 and v12 content is going to be archived.

Ah, my bad then. I'll remove it.

2021-07-16 01:11 UTC, J-Human commented
Ok, I'm really done.

2021-07-17 04:32 UTC, WiseDevHelper requested changes
`code-samples/event-handling/file-setup` -> `code-samples/event-handling/13/file-setup`

2021-07-17 04:33 UTC, J-Human commented
> `code-samples/event-handling/file-setup` -> `code-samples/event-handling/13/file-setup`

See Monbrey's comment above.

2021-07-17 04:35 UTC, WiseDevHelper commented
> > `code-samples/event-handling/file-setup` -> `code-samples/event-handling/13/file-setup`
> 
> See Monbrey's comment above.

Doesn't that refer to v12 folders?

2021-07-17 04:48 UTC, J-Human commented
> > > `code-samples/event-handling/file-setup` -> `code-samples/event-handling/13/file-setup`
> > 
> > 
> > See Monbrey's comment above.
> 
> Doesn't that refer to v12 folders (only)?

Right. I'll do your suggestion.

2021-07-17 04:53 UTC, J-Human commented
Perhaps it should be `.../file-setup/13/...` instead? Basing on the command handler part.

2021-07-17 04:58 UTC, J-Human commented
Alright, done.

2021-07-17 05:02 UTC, WiseDevHelper commented
> Perhaps it should be `.../file-setup/13/...` instead? Basing on the command handler part.

I guess that's fine but would like @Danktuary's input to confirm.

2021-07-17 05:02 UTC, J-Human commented
> > Perhaps it should be `.../file-setup/13/...` instead? Basing on the command handler part.
> 
> I guess that's fine but would like @Danktuary's input to confirm.

Already did it anyway. 😆

2021-07-19 01:33 UTC, Danktuary approved these changes

2021-07-19 09:09 UTC, merged