fix: Change interaction handler sample code
discordjs/guide pull request #769
Opened 2021-08-05 06:41 UTC by SinisterDeveloper

**Please describe the changes this PR makes and why it should be merged:**

I think this is a much better way to execute the Slash Commands. Instead of reading collection twice, this is a more simplified way

2021-08-05 06:58 UTC, DaStormer requested changes
To be honest, I think the current way is fine, but if we go with this, the paragraph under the code block needs to be adjusted accordingly.

Also, this messes up the code block line highlighting, but I can't suggest a change since it's outside the diff.

2021-08-05 06:58 UTC, DaStormer commented on guide/command-handling/README.md
> +	let command = client.commands.get(interaction.commandName);
```suggestion
	const command = client.commands.get(interaction.commandName);
```
Use `const` since `command` isn't being re-assigned.

2021-08-05 07:55 UTC, SinisterDeveloper commented on guide/command-handling/README.md
> +	let command = client.commands.get(interaction.commandName);
Alright

2021-08-05 11:54 UTC, PenPow approved these changes

2021-08-05 12:09 UTC, WiseDevHelper requested changes

2021-08-05 12:09 UTC, WiseDevHelper commented on guide/command-handling/README.md
>  client.on('interactionCreate', async interaction => {
The line above should be 
```
```js {4-13}
```

2021-08-05 13:32 UTC, SinisterDeveloper commented on guide/command-handling/README.md
>  client.on('interactionCreate', async interaction => {
Alright will fix

2021-08-05 23:59 UTC, almostSouji requested changes
- [x]  trailing spaces as per eslint
- [x]  text needs to be adapted, order of operations isn't accurate anymore

2021-08-07 11:16 UTC, WiseDevHelper approved these changes

2021-08-11 13:52 UTC, WiseDevHelper commented
This needs(?) a rebase.

2021-08-14 00:12 UTC, Danktuary reviewed
`/code-samples/command-handling/file-setup/13/index.js` needs to be updated to reflect the code changes

2021-08-14 00:12 UTC, Danktuary commented on guide/command-handling/README.md
> +And that's it! Whenever you want to add a new command, you [register a command](/interactions/registering-slash-commands.md), make a new file in your `commands` directory, name it with what you did f
```suggestion
And that's it! Whenever you want to add a new command, you [register a command](/interactions/registering-slash-commands.md), make a new file in your `commands` directory, name it the same as the slash command, and then do what you did for the other commands.
```

2021-08-16 14:58 UTC, Danktuary commented
Since I'll be rewriting this page in #826, I'll merge this now. Thanks for the PR. 😄

2021-08-16 14:59 UTC, merged