refactor: refactor command deployment & command handling
discordjs/guide pull request #786
Opened 2021-08-07 13:59 UTC by adrifcastr

**Please describe the changes this PR makes and why it should be merged:**
This PR refactors parts of the interactions and command handler sections:

- command handling uses builders to ease the deployment steps
- deployment has been refactored to use @discordjs/rest entirely and not rely on other methods
- command permissions no longer showcase the messageCreate event

2021-08-07 14:34 UTC, DaStormer commented
Is this a good idea? I feel like the guide should reflect the way to do this with discord.js as a “standalone.” 

These proposed changes may be misleading to new users as they may imply that the used packages are required, not just optional. Maybe a disclaimer or something that clearly shows it’s optional??

Idk, just my two cents.

2021-08-07 14:37 UTC, adrifcastr commented
> Is this a good idea? I feel like the guide should reflect the way to do this with discord.js as a “standalone.” 

It was discussed internally that this is the approach to go for

2021-08-07 15:37 UTC, iCrawl commented
Registering your commands should be a "separate" process.

How else are you going to do it? Let's say you don't have any slash commands, and no message intent.
Through the ready event? We cover extensively already that this is a bad idea.

So yes, having a deploy script that does all of this, great 👍

2021-08-08 10:33 UTC, Costpap commented
> Registering your commands should be a "separate" process.
> 
> How else are you going to do it? Let's say you don't have any slash commands, and no message intent.
> Through the ready event? We cover extensively already that this is a bad idea.
> 
> So yes, having a deploy script that does all of this, great 👍

Having a deploy script that does all of this is great, except for one concern. The script assumes that `client` is available in its context. For most of the users the guide caters to, this is notoriously difficult without them extensively modify their `index.js` file as well as the script. While I'm aware that making sure one's initiated client is available as context is something that could be considered out of scope for the guide, it'd be nice to see it covered. If it's not covered, I feel like as if it'll force users to complain about their code not working in various ways, which just creates an additional burden for everyone. Or, users will just manually register their commands by sending requests to the API on their own, if they know how to do so.

2021-08-08 18:03 UTC, Danktuary requested changes
Looks good overall 🎉 The page order and commands registration make better sense now

2021-08-08 18:25 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
> +First off, install the discord.js REST module by running `npm install @discordjs/rest` in your terminal.
```suggestion
First off, install the [discord.js REST module](https://github.com/discordjs/discord.js-modules/blob/main/packages/rest/) by running `npm install @discordjs/rest` in your terminal.
```

2021-08-08 18:25 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
> +In this section, we'll be using a script that is usable in conjunction with the slash command handler from the command handling section.
```suggestion
In this section, we'll be using a script that is usable in conjunction with the slash command handler from the [command handling](/command-handling/) section.
```

2021-08-08 18:59 UTC, Danktuary reviewed
Leftover lines from some of the last edits 😅

2021-08-08 18:59 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
>  	}
```suggestion
```

2021-08-08 18:59 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
```suggestion
```

2021-08-08 18:59 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
```suggestion
```

2021-08-08 18:59 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
```suggestion
```

2021-08-08 18:59 UTC, Danktuary commented on guide/interactions/registering-slash-commands.md
```suggestion
```

2021-08-08 19:05 UTC, Danktuary approved these changes

2021-08-10 22:59 UTC, muhimur9049 commented on guide/interactions/registering-slash-commands.md
>  If you already have slash commands set-up for your application and want to learn how to respond to them, refer to [the following page](/interactions/replying-to-slash-commands.md).
```suggestion
If you already have slash commands set up for your application and want to learn how to respond to them, refer to [the following page](/interactions/replying-to-slash-commands.md).
```
`set-up` doesn't seem to fit in this context

2021-08-10 23:26 UTC, merged