feat(Faq): Auto Stage Speaker
discordjs/guide pull request #832
Opened 2021-08-20 16:38 UTC by xHyroM

**Please describe the changes this PR makes and why it should be merged:**

I added an event that automatically sets the speaker if the bot connects to the stage channel.

2021-08-20 16:39 UTC, Gabe616 approved these changes

2021-08-21 15:13 UTC, tipakA commented
Assuming this would be needed to be in the FAQ, shouldn't this have some explanation or at least a mention to what it does or why it is included there?

2021-10-01 08:35 UTC, almostSouji requested changes
Please include some explanation as to why this is required

2022-05-07 14:19 UTC, xHyroM commented
https://github.com/discordjs/guide/pull/1099

2022-05-07 14:19 UTC, closed without merging