Updating Embed Guide
discordjs/guide pull request #976
Opened 2021-12-25 21:33 UTC by pab14567

Updating Embed Guide to show new usage of .setAuthor() method.

**Please describe the changes this PR makes and why it should be merged:**

2021-12-25 23:19 UTC, almeidx requested changes

2021-12-25 23:19 UTC, almeidx commented on guide/popular-topics/embeds.md
> +	.setAuthor({ name: 'Some name', iconURL: 'https://i.imgur.com/AfFp7pu.png', url: 'https://discord.js.org'})
```suggestion
	.setAuthor({ name: 'Some name', iconURL: 'https://i.imgur.com/AfFp7pu.png', url: 'https://discord.js.org' })
```

2021-12-26 09:53 UTC, MoonLGH approved these changes

2021-12-26 13:04 UTC, Underpants-dev approved these changes
👍

2021-12-27 02:03 UTC, merged